use burn::backend::autodiff::Autodiff;
use burn::backend::ndarray::NdArray;
use burn::optim::{AdamConfig, GradientsParams, Optimizer};
use burn::tensor::{Tensor, TensorData};

use super::{MafConfig, MAF};

type AD = Autodiff<NdArray<f32>>;

/// Train an MAF model and return both the model and the per-epoch loss history.
///
/// The loss history contains `(epoch, loss)` tuples sampled every `log_interval` epochs
/// and at the final epoch.
pub fn train_maf_with_data_and_log(
    maf_config: &MafConfig,
    params: Vec<f32>,
    features: Vec<f32>,
    n_epochs: usize,
    batch_size: usize,
) -> (MAF<AD>, Vec<(usize, f32)>) {
    let device = Default::default();
    let n_samples = params.len() / maf_config.param_dim;
    let feature_dim = features.len() / n_samples;

    let mut maf = MAF::<AD>::new(
        &device,
        maf_config.param_dim,
        feature_dim,
        maf_config.hidden_units,
        maf_config.n_flows,
    );

    let mut optimizer = AdamConfig::new().init::<AD, MAF<AD>>();
    let lr = maf_config.learning_rate;

    let mut indices: Vec<usize> = (0..n_samples).collect();
    let mut loss_history: Vec<(usize, f32)> = Vec::new();

    for epoch in 0..n_epochs {
        use rand::seq::SliceRandom;
        indices.shuffle(&mut rand::thread_rng());

        for batch_start in (0..n_samples).step_by(batch_size) {
            let batch_end = (batch_start + batch_size).min(n_samples);
            let batch_indices = &indices[batch_start..batch_end];
            let current_batch_size = batch_indices.len();

            let mut params_batch = Vec::with_capacity(current_batch_size * maf_config.param_dim);
            let mut features_batch = Vec::with_capacity(current_batch_size * feature_dim);

            for &i in batch_indices {
                for d in 0..maf_config.param_dim {
                    params_batch.push(params[i * maf_config.param_dim + d]);
                }
                for d in 0..feature_dim {
                    features_batch.push(features[i * feature_dim + d]);
                }
            }

            let params_tensor = Tensor::<AD, 2>::from_data(
                TensorData::new::<f32, Vec<usize>>(
                    params_batch,
                    vec![current_batch_size, maf_config.param_dim],
                ),
                &device,
            );

            let features_tensor = Tensor::<AD, 2>::from_data(
                TensorData::new::<f32, Vec<usize>>(
                    features_batch,
                    vec![current_batch_size, feature_dim],
                ),&device,
            );

            let log_prob = maf.forward_log_prob(params_tensor, features_tensor);
            let loss = log_prob.neg().mean();

            let grads = loss.backward();
            let grads = GradientsParams::from_grads(grads, &maf);
            maf = optimizer.step(lr, maf, grads);
        }

        if epoch % 5 == 0 || epoch == n_epochs - 1 {
            let epoch_loss = compute_epoch_loss(
                &maf, &params, &features, maf_config.param_dim, feature_dim, n_samples, &device);
            log::info!("SBI epoch {}/{}  loss={:.4}", epoch + 1, n_epochs, epoch_loss);
            loss_history.push((epoch, epoch_loss));
        }
    }

    (maf, loss_history)
}

/// Train an MAF model on (parameters, features) pairs using Adam.
pub fn train_maf_with_data(
    maf_config: &MafConfig,
    params: Vec<f32>,
    features: Vec<f32>,
    n_epochs: usize,
    batch_size: usize,
) -> MAF<AD> {
    train_maf_with_data_and_log(maf_config, params, features, n_epochs, batch_size).0
}

fn compute_epoch_loss(
    maf: &MAF<AD>,
    params: &[f32],
    features: &[f32],
    param_dim: usize,
    feature_dim: usize,
    n_samples: usize,
    device: &<AD as burn::tensor::backend::Backend>::Device,
) -> f32 {
    let mut total = 0.0f32;
    for i in 0..n_samples {
        let p = &params[i * param_dim..(i + 1) * param_dim];
        let f = &features[i * feature_dim..(i + 1) * feature_dim];
        let params_tensor = Tensor::<AD, 2>::from_data(
            TensorData::new::<f32, Vec<usize>>(p.to_vec(), vec![1, param_dim]),
            device,
        );
        let features_tensor = Tensor::<AD, 2>::from_data(
            TensorData::new::<f32, Vec<usize>>(f.to_vec(), vec![1, feature_dim]),
            device,
        );
        let log_prob = maf.forward_log_prob(params_tensor, features_tensor);
        let loss = log_prob.neg().mean();
        total += loss.into_data().as_slice::<f32>().unwrap()[0];
    }
    total / n_samples as f32
}

/// Training entry point for the MAF model.
///
/// NOTE: This function requires pre-computed (params, features) training data
/// which must be generated by running a parameter sweep first.
/// For end-to-end SBI workflow, use `hyburn pipeline` which handles
/// sweep → features → training automatically.
pub fn train_maf(config: &MafConfig) -> anyhow::Result<()> {
    anyhow::bail!(
        "Direct MAF training requires pre-generated data. \
         Use `hyburn pipeline` for end-to-end SBI workflow, \
         or call `train_maf_with_data` / `train_maf_with_data_and_log` programmatically. \
         Config: {:?}",
        config
    );
}

/// Inference entry point: load a saved MAF record and sample the posterior.
///
/// NOTE: Model record loading and full inference pipeline are not yet implemented.
/// For posterior visualization, use `hyburn sbi-report`.
pub fn infer_maf(
    model_path: &str,
    features_path: &str,
    n_samples: usize,
) -> anyhow::Result<()> {
    anyhow::bail!(
        "MAF inference from saved records is not yet implemented. \
         Use `hyburn sbi-report` for posterior visualization, \
         or `hyburn pipeline` for the full sweep → train → infer workflow. \
         (args: model={}, features={}, n_samples={})",
        model_path, features_path, n_samples
    );
}
