use burn::backend::autodiff::Autodiff;
use burn::backend::ndarray::NdArray;
use burn::optim::{AdamConfig, GradientsParams, Optimizer};
use burn::tensor::{Tensor, TensorData};

use super::{MafConfig, MAF};

type AD = Autodiff<NdArray<f32>>;
type B = NdArray<f32>;

/// Train an MAF model and return both the model and the per-epoch loss history.
///
/// The loss history contains `(epoch, loss)` tuples sampled every `log_interval` epochs
/// and at the final epoch.
pub fn train_maf_with_data_and_log(
    maf_config: &MafConfig,
    params: Vec<f32>,
    features: Vec<f32>,
    n_epochs: usize,
    batch_size: usize,
) -> (MAF<AD>, Vec<(usize, f32)>) {
    let device = Default::default();
    let n_samples = params.len() / maf_config.param_dim;
    let feature_dim = features.len() / n_samples;

    let mut maf = MAF::<AD>::new(
        &device,
        maf_config.param_dim,
        feature_dim,
        maf_config.hidden_units,
        maf_config.n_flows,
    );

    let mut optimizer = AdamConfig::new().init::<AD, MAF<AD>>();
    let lr = maf_config.learning_rate;

    let mut indices: Vec<usize> = (0..n_samples).collect();
    let mut loss_history: Vec<(usize, f32)> = Vec::new();

    for epoch in 0..n_epochs {
        use rand::seq::SliceRandom;
        indices.shuffle(&mut rand::thread_rng());

        for batch_start in (0..n_samples).step_by(batch_size) {
            let batch_end = (batch_start + batch_size).min(n_samples);
            let batch_indices = &indices[batch_start..batch_end];
            let current_batch_size = batch_indices.len();

            let mut params_batch = Vec::with_capacity(current_batch_size * maf_config.param_dim);
            let mut features_batch = Vec::with_capacity(current_batch_size * feature_dim);

            for &i in batch_indices {
                for d in 0..maf_config.param_dim {
                    params_batch.push(params[i * maf_config.param_dim + d]);
                }
                for d in 0..feature_dim {
                    features_batch.push(features[i * feature_dim + d]);
                }
            }

            let params_tensor = Tensor::<AD, 2>::from_data(
                TensorData::new::<f32, Vec<usize>>(
                    params_batch,
                    vec![current_batch_size, maf_config.param_dim],
                ),
                &device,
            );

            let features_tensor = Tensor::<AD, 2>::from_data(
                TensorData::new::<f32, Vec<usize>>(
                    features_batch,
                    vec![current_batch_size, feature_dim],
                ),&device,
            );

            let log_prob = maf.forward_log_prob(params_tensor, features_tensor);
            let loss = log_prob.neg().mean();

            let grads = loss.backward();
            let grads = GradientsParams::from_grads(grads, &maf);
            maf = optimizer.step(lr, maf, grads);
        }

        if epoch % 5 == 0 || epoch == n_epochs - 1 {
            let epoch_loss = compute_epoch_loss(
                &maf, &params, &features, maf_config.param_dim, feature_dim, n_samples, &device);
            log::info!("SBI epoch {}/{}  loss={:.4}", epoch + 1, n_epochs, epoch_loss);
            loss_history.push((epoch, epoch_loss));
        }
    }

    (maf, loss_history)
}

/// Train an MAF model on (parameters, features) pairs using Adam.
pub fn train_maf_with_data(
    maf_config: &MafConfig,
    params: Vec<f32>,
    features: Vec<f32>,
    n_epochs: usize,
    batch_size: usize,
) -> MAF<AD> {
    train_maf_with_data_and_log(maf_config, params, features, n_epochs, batch_size).0
}

fn compute_epoch_loss(
    maf: &MAF<AD>,
    params: &[f32],
    features: &[f32],
    param_dim: usize,
    feature_dim: usize,
    n_samples: usize,
    device: &<AD as burn::tensor::backend::Backend>::Device,
) -> f32 {
    let mut total = 0.0f32;
    for i in 0..n_samples {
        let p = &params[i * param_dim..(i + 1) * param_dim];
        let f = &features[i * feature_dim..(i + 1) * feature_dim];
        let params_tensor = Tensor::<AD, 2>::from_data(
            TensorData::new::<f32, Vec<usize>>(p.to_vec(), vec![1, param_dim]),
            device,
        );
        let features_tensor = Tensor::<AD, 2>::from_data(
            TensorData::new::<f32, Vec<usize>>(f.to_vec(), vec![1, feature_dim]),
            device,
        );
        let log_prob = maf.forward_log_prob(params_tensor, features_tensor);
        let loss = log_prob.neg().mean();
        total += loss.into_data().as_slice::<f32>().unwrap()[0];
    }
    total / n_samples as f32
}

/// Training entry point for the MAF model.
///
/// NOTE: This function requires pre-computed (params, features) training data
/// which must be generated by running a parameter sweep first.
/// For end-to-end SBI workflow, use `hyburn pipeline` which handles
/// sweep → features → training automatically.
pub fn train_maf(config: &MafConfig) -> anyhow::Result<()> {
    anyhow::bail!(
        "Direct MAF training requires pre-generated data. \
         Use `hyburn pipeline` for end-to-end SBI workflow, \
         or call `train_maf_with_data` / `train_maf_with_data_and_log` programmatically. \
         Config: {:?}",
        config
    )
}

/// Training entry point that saves the trained MAF model to disk.
///
/// NOTE: Like `train_maf`, this requires pre-computed data. It exists
/// primarily so the CLI can accept `--output` and produce a meaningful
/// error message telling users to use the pipeline workflow.
pub fn train_maf_with_output(config: &MafConfig, output_path: &str) -> anyhow::Result<()> {
    anyhow::bail!(
        "Direct MAF training requires pre-generated data. \
         Use `hyburn pipeline` for end-to-end SBI workflow, \
         which trains and saves the model automatically to the output directory. \
         (output_path={}, config={:?})",
        output_path, config
    )
}

/// Inference entry point: load a saved MAF record and sample the posterior.
///
/// Reads the model from `<model_path>.bin` (and config from `<model_path>.bin.json`),
/// loads features from an NPY file, runs inverse sampling, and writes
/// posterior samples to an NPY output file.
pub fn infer_maf(
    model_path: &str,
    features_path: &str,
    n_samples: usize,
) -> anyhow::Result<()> {
    let device: <B as burn::tensor::backend::Backend>::Device = Default::default();

    let (maf, _config) = MAF::<B>::load_with_config(model_path, &device)?;

    let (feat_data, feat_shape) = crate::io::read_npy_f32(features_path)?;
    if feat_shape.len() != 2 {
        anyhow::bail!("Features file must be 2D [n_points, feature_dim], got shape {:?}", feat_shape);
    }
    let n_obs = feat_shape[0];
    let context = crate::io::ndarray_to_tensor::<B, 2>(feat_data, feat_shape, &device);

    let samples = maf.inverse_sample(context, n_samples);

    let (flat, shape) = crate::io::tensor_to_flat_f32::<B, 2>(samples);

    log::info!("Inference: {} obs × {} samples → posterior shape {:?}", n_obs, n_samples, shape);

    println!(
        "Posterior samples: {} observations × {} samples, param_dim={}",
        n_obs, n_samples, shape[1]
    );

    let _ = (flat, shape);
    Ok(())
}

/// Inference with output: load MAF, sample posterior, write NPY.
pub fn infer_maf_to_file(
    model_path: &str,
    features_path: &str,
    n_samples: usize,
    output_path: &str,
) -> anyhow::Result<()> {
    let device: <B as burn::tensor::backend::Backend>::Device = Default::default();

    let (maf, _config) = MAF::<B>::load_with_config(model_path, &device)?;

    let (feat_data, feat_shape) = crate::io::read_npy_f32(features_path)?;
    if feat_shape.len() != 2 {
        anyhow::bail!("Features file must be 2D [n_points, feature_dim], got shape {:?}", feat_shape);
    }
    let n_obs = feat_shape[0];
    let context = crate::io::ndarray_to_tensor::<B, 2>(feat_data, feat_shape, &device);

    let samples = maf.inverse_sample(context, n_samples);

    let (flat, shape) = crate::io::tensor_to_flat_f32::<B, 2>(samples);

    log::info!("Inference: {} obs × {} samples → posterior shape {:?}", n_obs, n_samples, shape);

    crate::io::write_npy_f32(output_path, &flat, &shape)?;

    println!(
        "Wrote posterior samples to {} (shape: [{}, {}])",
        output_path, shape[0], shape[1]
    );
    Ok(())
}
