/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_engineinfo_free: (a: number, b: number) => void;
export const __wbg_webengine_free: (a: number, b: number) => void;
export const engineinfo_dt: (a: number) => number;
export const engineinfo_n_bold_monitors: (a: number) => number;
export const engineinfo_n_subnetworks: (a: number) => number;
export const engineinfo_nmodes: (a: number) => number;
export const engineinfo_nnodes: (a: number) => number;
export const engineinfo_nvar: (a: number) => number;
export const engineinfo_total_steps: (a: number) => number;
export const model_default_params: (a: number, b: number) => [number, number, number, number];
export const model_registry_json: () => [number, number];
export const run_sbi_json: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
export const validate_config_json: (a: number, b: number) => [number, number];
export const validate_config_toml: (a: number, b: number) => [number, number];
export const webengine_all_states: (a: number) => any;
export const webengine_bold_signal: (a: number) => any;
export const webengine_bold_volumes: (a: number) => number;
export const webengine_current_state: (a: number) => any;
export const webengine_current_step: (a: number) => number;
export const webengine_dt: (a: number) => number;
export const webengine_from_json: (a: number, b: number) => [number, number, number];
export const webengine_from_toml: (a: number, b: number) => [number, number, number];
export const webengine_info: (a: number) => number;
export const webengine_integrator: (a: number) => [number, number];
export const webengine_n_subnetworks: (a: number) => number;
export const webengine_nsig: (a: number) => number;
export const webengine_step: (a: number) => void;
export const webengine_step_n: (a: number, b: number) => void;
export const webengine_steps_run: (a: number) => number;
export const webengine_subnetwork_nmodes: (a: number, b: number) => number;
export const webengine_subnetwork_nnodes: (a: number, b: number) => number;
export const webengine_subnetwork_nvar: (a: number, b: number) => number;
export const webengine_trajectory: (a: number) => any;
export const webengine_trajectory_len: (a: number) => number;
export const init_logger: () => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
